// ===========================================================================
// 地圖產生器 (real-geography map generator) — 多旅程版
// ---------------------------------------------------------------------------
// 把 Natural Earth 50m 的真實國界海岸線，投影成棋盤用的 SVG 路徑，並依「真實
// 經緯度」重新計算每一站的座標，寫回各 journey JSON。
//
//   輸入：scripts/_geodata/ne50m_countries.geojson  (下載自 Natural Earth)
//   輸出（每條旅程一組）：
//     journey1 → src/data/region-map.json   + 寫回 journey1.json
//     journey2 → src/data/region-map2.json  + 寫回 journey2.json
//
// 投影：等距圓柱投影 (equirectangular)，經度乘上 cos(中央緯度) 修正寬窄，
//       再各自正規化到 0~100。棋盤容器的長寬比設為 aspect 即可避免變形。
// 執行：node scripts/gen-map.mjs
// ===========================================================================
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const GEO = join(__dirname, '_geodata', 'ne50m_countries.geojson')
const DATA = join(__dirname, '..', 'src', 'data')

const GEO_URL =
  'https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_50m_admin_0_countries.geojson'

async function ensureGeoData() {
  if (existsSync(GEO)) return
  console.log('⬇️  找不到地理資料，正在下載 Natural Earth 50m 國界（約 3MB，僅第一次）...')
  mkdirSync(dirname(GEO), { recursive: true })
  const res = await fetch(GEO_URL)
  if (!res.ok) throw new Error(`下載失敗 (HTTP ${res.status})：${GEO_URL}`)
  const buf = Buffer.from(await res.arrayBuffer())
  writeFileSync(GEO, buf)
  console.log(`   已存到 ${GEO}（${(buf.length / 1024 / 1024).toFixed(2)} MB）`)
}
await ensureGeoData()

const fc = JSON.parse(readFileSync(GEO, 'utf-8'))
const r1 = (n) => Math.round(n * 10) / 10

// --- Sutherland–Hodgman：把多邊形裁切到 [0,100]×[0,100] 方框（與投影無關，共用） ---
const lerp = (a, b, t) => [a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t]
function clipEdge(pts, inside, isect) {
  const out = []
  for (let i = 0; i < pts.length; i++) {
    const cur = pts[i]
    const prev = pts[(i + pts.length - 1) % pts.length]
    const cIn = inside(cur), pIn = inside(prev)
    if (cIn) {
      if (!pIn) out.push(isect(prev, cur))
      out.push(cur)
    } else if (pIn) {
      out.push(isect(prev, cur))
    }
  }
  return out
}
function clipToBox(pts) {
  pts = clipEdge(pts, (p) => p[0] >= 0,   (a, b) => lerp(a, b, (0 - a[0]) / (b[0] - a[0])))
  if (!pts.length) return pts
  pts = clipEdge(pts, (p) => p[0] <= 100, (a, b) => lerp(a, b, (100 - a[0]) / (b[0] - a[0])))
  if (!pts.length) return pts
  pts = clipEdge(pts, (p) => p[1] >= 0,   (a, b) => lerp(a, b, (0 - a[1]) / (b[1] - a[1])))
  if (!pts.length) return pts
  pts = clipEdge(pts, (p) => p[1] <= 100, (a, b) => lerp(a, b, (100 - a[1]) / (b[1] - a[1])))
  return pts
}
function decimate(pts, eps = 0.25) {
  const out = []
  for (const p of pts) {
    const last = out[out.length - 1]
    if (!last || Math.hypot(p[0] - last[0], p[1] - last[1]) >= eps) out.push(p)
  }
  return out
}

// 產生一個旅程的地圖：投影海岸線 + 寫回站點座標。
function buildRegion(cfg) {
  const { label, bounds, iso, cities, journeyFile, mapFile } = cfg
  const { lonMin, lonMax, latMin, latMax } = bounds
  const midLat = (latMin + latMax) / 2
  const K = Math.cos((midLat * Math.PI) / 180) // 經度壓縮係數
  const aspect = ((lonMax - lonMin) * K) / (latMax - latMin) // 棋盤寬/高
  const project = (lon, lat) => [
    ((lon - lonMin) / (lonMax - lonMin)) * 100,
    ((latMax - lat) / (latMax - latMin)) * 100,
  ]
  const ringToPath = (ring) => {
    let clipped = clipToBox(ring.map(([lon, lat]) => project(lon, lat)))
    if (clipped.length < 3) return null
    clipped = decimate(clipped)
    if (clipped.length < 3) return null
    return 'M' + clipped.map(([x, y]) => `${r1(x)},${r1(y)}`).join(' L') + ' Z'
  }

  const isoSet = new Set(iso)
  const wanted = (props) => {
    const codes = [props.ISO_A3, props.ADM0_A3, props.ISO_A3_EH, props.SOV_A3]
    return codes.some((c) => isoSet.has(c))
  }

  const lands = []
  for (const f of fc.features) {
    if (!wanted(f.properties)) continue
    const g = f.geometry
    const polys = g.type === 'Polygon' ? [g.coordinates] : g.type === 'MultiPolygon' ? g.coordinates : []
    for (const poly of polys) {
      const d = ringToPath(poly[0]) // 只取外環
      if (d) lands.push(d)
    }
  }

  const cityMarks = Object.fromEntries(
    Object.entries(cities).map(([id, { lat, lon }]) => {
      const [x, y] = project(lon, lat)
      return [id, { x: r1(x), y: r1(y), lat, lon }]
    }),
  )

  // 地名標籤：由真實經緯度投影成棋盤座標，所以「賽普勒斯」之類一定落在對的位置。
  const labelMarks = (cfg.labels || []).map((l) => {
    const [x, y] = project(l.lon, l.lat)
    return { t: l.t, x: r1(x), y: r1(y), kind: l.kind }
  })

  writeFileSync(
    join(DATA, mapFile),
    JSON.stringify(
      {
        _comment: 'Auto-generated by scripts/gen-map.mjs — do not edit by hand. Run: node scripts/gen-map.mjs',
        projection: { lonMin, lonMax, latMin, latMax, midLat },
        aspect: Math.round(aspect * 1000) / 1000,
        lands,
        cities: cityMarks,
        labels: labelMarks,
      },
      null,
      2,
    ),
  )

  const journey = JSON.parse(readFileSync(join(DATA, journeyFile), 'utf-8'))
  let patched = 0
  for (const st of journey.stations) {
    const c = cities[st.id]
    if (!c) {
      console.warn(`⚠️  ${journeyFile} 有一站沒對應到城市座標：${st.id}`)
      continue
    }
    const [x, y] = project(c.lon, c.lat)
    st.x = r1(x)
    st.y = r1(y)
    st.lat = c.lat
    st.lon = c.lon
    patched++
  }
  writeFileSync(join(DATA, journeyFile), JSON.stringify(journey, null, 2) + '\n')

  console.log(
    `✅ ${label}：國界 ${lands.length} 條、aspect ${Math.round(aspect * 1000) / 1000}、座標 ${patched}/${journey.stations.length} 站`,
  )
}

// ===========================================================================
// 第一次宣教旅程（東地中海一帶）—— 維持原本的範圍與城市，輸出不變。
// ===========================================================================
buildRegion({
  label: '第一次旅程',
  bounds: { lonMin: 29.0, lonMax: 38.2, latMin: 33.6, latMax: 39.2 },
  iso: ['TUR', 'SYR', 'LBN', 'CYP', 'CYN'], // 含北賽普勒斯讓整座島完整
  journeyFile: 'journey1.json',
  mapFile: 'region-map.json',
  labels: [
    { t: '小亞細亞（今土耳其）', lat: 38.9, lon: 33.6, kind: 'region' },
    { t: '敘利亞', lat: 35.4, lon: 37.7, kind: 'region' },
    { t: '賽普勒斯', lat: 35.05, lon: 33.3, kind: 'island' },
    { t: '居比路', lat: 34.6, lon: 33.3, kind: 'island-sub' },
    { t: '地　中　海', lat: 34.0, lon: 33.9, kind: 'sea' },
  ],
  cities: {
    antioch_start:    { lat: 36.20, lon: 36.16 },
    seleucia:         { lat: 36.12, lon: 35.93 },
    salamis:          { lat: 35.18, lon: 33.91 },
    paphos:           { lat: 34.77, lon: 32.41 },
    perga:            { lat: 36.96, lon: 30.85 },
    pisidian_antioch: { lat: 38.31, lon: 31.19 },
    iconium:          { lat: 37.87, lon: 32.49 },
    lystra:           { lat: 37.58, lon: 32.45 },
    derbe:            { lat: 37.35, lon: 33.28 },
    return_strengthen:{ lat: 37.70, lon: 31.95 },
    attalia:          { lat: 36.88, lon: 30.70 },
    antioch_end:      { lat: 36.42, lon: 36.40 },
    seacard_1:        { lat: 35.65, lon: 34.92 },
    seacard_2:        { lat: 35.87, lon: 31.63 },
    mountain_run:     { lat: 37.64, lon: 31.02 },
    landcard_1:       { lat: 38.09, lon: 31.84 },
    landcard_2:       { lat: 37.47, lon: 32.87 },
    landcard_3:       { lat: 37.29, lon: 31.33 },
    storm_challenge:  { lat: 36.76, lon: 32.13 },
    seacard_3:        { lat: 36.65, lon: 33.55 },
  },
})

// ===========================================================================
// 第二次宣教旅程（東地中海 + 愛琴海 + 希臘/馬其頓）—— 框架更往西，含歐洲。
// ===========================================================================
buildRegion({
  label: '第二次旅程',
  bounds: { lonMin: 21.0, lonMax: 37.5, latMin: 31.5, latMax: 41.8 },
  // 希臘、土耳其、敘利亞、黎巴嫩、賽普勒斯、以色列/巴勒斯坦、約旦、埃及、巴爾幹諸國（畫出愛琴海與希臘海岸線）
  iso: ['GRC', 'TUR', 'SYR', 'LBN', 'CYP', 'CYN', 'ISR', 'PSE', 'JOR', 'EGY', 'BGR', 'MKD', 'ALB'],
  journeyFile: 'journey2.json',
  mapFile: 'region-map2.json',
  labels: [
    { t: '馬其頓', lat: 41.0, lon: 23.2, kind: 'region' },
    { t: '亞該亞（希臘）', lat: 38.1, lon: 22.6, kind: 'region' },
    { t: '小亞細亞', lat: 38.9, lon: 30.5, kind: 'region' },
    { t: '敘利亞', lat: 35.8, lon: 36.6, kind: 'region' },
    { t: '愛　琴　海', lat: 38.6, lon: 25.1, kind: 'sea' },
    { t: '地　中　海', lat: 33.6, lon: 28.5, kind: 'sea' },
  ],
  cities: {
    antioch2_start: { lat: 36.20, lon: 36.16 }, // 敘利亞安提阿（出發）
    derbe2:         { lat: 37.35, lon: 33.28 }, // 特庇
    lystra2:        { lat: 37.58, lon: 32.45 }, // 路司得（提摩太加入）
    troas:          { lat: 39.78, lon: 26.16 }, // 特羅亞（馬其頓異象）
    philippi:       { lat: 41.01, lon: 24.29 }, // 腓立比（歐洲第一間教會）
    thessalonica:   { lat: 40.64, lon: 22.94 }, // 帖撒羅尼迦
    berea:          { lat: 40.52, lon: 22.20 }, // 庇哩亞
    athens:         { lat: 37.98, lon: 23.73 }, // 雅典（亞略巴古）
    corinth:        { lat: 37.91, lon: 22.88 }, // 哥林多（住一年半）
    ephesus2:       { lat: 37.94, lon: 27.34 }, // 以弗所（短暫停留）
    caesarea2:      { lat: 32.50, lon: 34.89 }, // 該撒利亞（回程登岸）
    antioch2_end:   { lat: 36.42, lon: 36.40 }, // 回到安提阿（旅程結束）
  },
})
